### ISSUE TITLE
Need help in getting this working

### ISSUE THREAD

**Issue by mhatrey** [LeJeko/homebridge-enlighten-power#1]
Hello @LeJeko 

I installed the plugin and added the `bonjour` code in the accessories config. Upon restarting I get the following error

```
TypeError: Cannot read property 'statusCode' of undefined
    at AirQualityAccessory.<anonymous> (/homebridge/node_modules/homebridge-enlighten-power/index.js:87:77)
    at self.callback (/homebridge/node_modules/homebridge-enlighten-power/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.onRequestError (/homebridge/node_modules/homebridge-enlighten-power/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by LeJeko** [comment]
Hi @mhatrey,
Can you try with "Custom url" setup ?
Thank you
